'use strict';

const { MONTH_NAMES } = require('./attendanceParse');

function periodLabel(month, year) {
    const m = Number(month);
    const y = Number(year);
    if (!m || !y) return '';
    return `${MONTH_NAMES[m - 1]} ${y}`;
}

function money(n) {
    if (n == null || Number.isNaN(Number(n))) return '—';
    return Math.round(Number(n)).toLocaleString('en-PK');
}

function filterPayrollRowsForSite(rows, siteCode, siteName) {
    const code = String(siteCode || '').trim().toUpperCase();
    const nameNeedle = String(siteName || '').trim().toLowerCase();
    const filtered = (rows || []).filter((r) => {
        const site = String(r.site || r.location || '').trim().toUpperCase();
        if (code && site === code) return true;
        if (nameNeedle) {
            const loc = String(r.location || r.site || '').toLowerCase();
            if (loc.includes(nameNeedle) || loc.includes(code.toLowerCase())) return true;
        }
        return false;
    });
    return filtered.length ? filtered : (rows || []);
}

function renderSitePayrollHtml({
    siteName,
    siteCode,
    month,
    year,
    contractName,
    rows = [],
}) {
    const period = periodLabel(month, year);
    const displaySite = siteName || siteCode || 'Site';
    let totalNet = 0;
    let totalGross = 0;

    const bodyRows = rows.map((r) => {
        const c = r.computed || {};
        const present = r.inputs?.present_days ?? r.paid_days;
        const absent = r.inputs?.absent_days ?? c.modelA?.absentDays;
        const net = Number(c.netPay || 0);
        const gross = Number(c.gross || 0);
        totalNet += net;
        totalGross += gross;
        return `
          <tr>
            <td>${r.employee_id || '—'}</td>
            <td>${r.employee_name || '—'}</td>
            <td>${r.designation || '—'}</td>
            <td class="num">${present != null ? present : '—'}</td>
            <td class="num">${absent != null ? absent : '—'}</td>
            <td class="num">${money(c.salaryForDays ?? r.basic_salary)}</td>
            <td class="num">${money(c.eobiEmployee)}</td>
            <td class="num">${money(c.wht)}</td>
            <td class="num">${money(gross)}</td>
            <td class="num"><strong>${money(net)}</strong></td>
          </tr>`;
    }).join('');

    return `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Payroll ${displaySite} ${period}</title>
<style>
  @page { size: A4 landscape; margin: 10mm; }
  body { font-family: Arial, Helvetica, sans-serif; color: #0f172a; font-size: 11px; }
  h1 { font-size: 18px; margin: 0 0 4px; }
  .meta { color: #475569; margin-bottom: 12px; }
  table { width: 100%; border-collapse: collapse; }
  th, td { border: 1px solid #cbd5e1; padding: 6px 8px; text-align: left; }
  th { background: #1a2332; color: #e8eef7; font-size: 10px; text-transform: uppercase; }
  .num { text-align: right; white-space: nowrap; }
  tfoot td { font-weight: 700; background: #f8fafc; }
</style></head><body>
  <h1>Monthly Payroll — ${displaySite}</h1>
  <div class="meta">${contractName || 'Fixed Value Contract'} · ${period} · ${rows.length} employees</div>
  <table>
    <thead><tr>
      <th>Staff code</th><th>Name</th><th>Designation</th>
      <th>Present</th><th>Absent</th><th>Wages</th><th>EOBI</th><th>Tax</th><th>Gross</th><th>Net pay</th>
    </tr></thead>
    <tbody>${bodyRows || '<tr><td colspan="10">No payroll rows for this site.</td></tr>'}</tbody>
    <tfoot><tr>
      <td colspan="8">Site totals</td>
      <td class="num">${money(totalGross)}</td>
      <td class="num">${money(totalNet)}</td>
    </tr></tfoot>
  </table>
  <p style="margin-top:12px;color:#64748b;font-size:10px;">Generated by ASIL HCM — attendance-based payroll (absent-driven deductions).</p>
</body></html>`;
}

module.exports = {
    periodLabel,
    filterPayrollRowsForSite,
    renderSitePayrollHtml,
};
